printwavbytes : printwavbytes.cpp 
	g++ -o printwavbytes printwavbytes.cpp

test : printwavbytes
	./printwavbytes

fail : printwavbytes
	./printwavbytes nonexistantfile.wav

rm :
	rm printwavbytes